[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd frontend && npm ci --prefer-offline --no-audit']

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd frontend && npm start'
